name: commit-artifact

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

    push:
    build:
        name: Publish Stable
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Setup Environment
              run: node -e "console.log('PACKAGE_VERSION=' + require('./package.json').version + '\nPACKAGE_NAME=' + require('./package.json').name + '-' + require('./package.json').version)" >> $GITHUB_ENV
            - name: Verify versions
              run: node -e "if ('refs/tags/v' + '${{ env.PACKAGE_VERSION }}' !== '${{ github.ref }}') { console.log('::error' + 'Version Mismatch. refs/tags/v' + '${{ env.PACKAGE_VERSION }}', '${{ github.ref }}'); throw Error('Version Mismatch')} "
            - name: Install
              run: npm install
            - name: Package extension
              run: npm install vsce
            - name: Publish Extension
              run: |
                npx vsce package
                yarn vsce publish --yarn --packagePath ./${{ env.PACKAGE_NAME }}.vsix -p ${{ secrets.MARKETPLACE_PAT }}
                npx ovsx publish ./${{ env.PACKAGE_NAME }}.vsix -p ${{ secrets.OVSX_ACCESS_TOKEN }}
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v2
              with:
                  name: {{ env.PACKAGE_NAME }}.vsix
                  path: dothttp-runner-preview-notebook.vsix
                  retention-days: 30